server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    url: jdbc:mariadb://localhost:3306/registration
    password: MYSql@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MariaDBDialect
          format_sql: true
        show_sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
